name: TEST_01
use_tb_logger: true
model: IRN
distortion: sr
scale: 2
gpu_ids: [0]

datasets:
  train:
    name: DIV2K
    mode: LQGT
    dataroot_GT: datasets/Set14
    dataroot_LQ: ~

    use_shuffle: true
    n_workers: 4
    batch_size: 2
    GT_size: 144
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: val_DIV2K
    mode: LQGT
    dataroot_GT: datasets/Set14
    dataroot_LQ: ~

network_G:
  which_model_G:
    subnet_type: DBNet
  in_nc: 3
  out_nc: 3
  block_num: [8]
  scale: 2
  init: xavier

path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

train:
  lr_G: !!float 2e-4
  beta1: 0.9
  beta2: 0.999
  niter: 500000

  pixel_criterion_forw: l2
  pixel_criterion_back: l1

  val_freq: !!float 5e3

  lambda_fit_forw: 4.
  lambda_rec_back: 1
  lambda_ce_forw: 1
  weight_decay_G: !!float 1e-5
  gradient_clipping: 10

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3