name: TEST_01
use_tb_logger: true
model: IRN
distortion: sr
scale: 2
gpu_ids: [0]

datasets:
  train:
    name: DIV2K
    mode: LQGT
    dataroot_GT: datasets/Set14
    dataroot_LQ: ~

    use_shuffle: true
    n_workers: 4
    batch_size: 8
    GT_size: 144
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: val_DIV2K
    mode: LQGT
    dataroot_GT: ~
    dataroot_LQ: ~

network_G:
  which_model_G:
    subnet_type: DBNet
  in_nc: 3
  out_nc: 3
  block_num: [8]
  scale: 2
  init: xavier

train:
  niter: 500000